<?php

function surprise_tutorial_menu(){
    $items['surprise_tutorial'] = array(
        'title' => 'Surprise Me!',
        'page callback' => 'random_tutorial',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function random_tutorial(){
    //use content/tutorial + wildcard for redirect
    //might need to get array of all tutorials
    $tutorials = array('jaynes-hat', 'rfid-cat-door', 'fairy-lanterns', 'lavender-bath-salts');

    //picks random index from array
    $random_pick = array_rand($tutorials);
    $random_tutorial = $tutorials[$random_pick];


    $url = 'content/tutorial/' . $random_tutorial;
    drupal_goto($url);

}
